apiVersion: v1
kind: Service
metadata:
  name: api-frontend
  labels:
    app: api
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: api
    tier: frontend